// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSuF849TUDyyskuWBlsWiS119qTC4JwKU',
    appId: '1:287052139238:web:c3e130bf532c3e2d348927',
    messagingSenderId: '287052139238',
    projectId: 'walltutorial-6fa05',
    authDomain: 'walltutorial-6fa05.firebaseapp.com',
    storageBucket: 'walltutorial-6fa05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoc3QOr4bvMwuDOcnNNNDPoRlXGwkyABQ',
    appId: '1:287052139238:android:5cef0e846ea3969e348927',
    messagingSenderId: '287052139238',
    projectId: 'walltutorial-6fa05',
    storageBucket: 'walltutorial-6fa05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCpy3JYHhesed1l1mvbXCteaE7cXMq2F4',
    appId: '1:287052139238:ios:b78cde96d7aba9df348927',
    messagingSenderId: '287052139238',
    projectId: 'walltutorial-6fa05',
    storageBucket: 'walltutorial-6fa05.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCpy3JYHhesed1l1mvbXCteaE7cXMq2F4',
    appId: '1:287052139238:ios:b78cde96d7aba9df348927',
    messagingSenderId: '287052139238',
    projectId: 'walltutorial-6fa05',
    storageBucket: 'walltutorial-6fa05.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSuF849TUDyyskuWBlsWiS119qTC4JwKU',
    appId: '1:287052139238:web:4ca5719ff7bfedfb348927',
    messagingSenderId: '287052139238',
    projectId: 'walltutorial-6fa05',
    authDomain: 'walltutorial-6fa05.firebaseapp.com',
    storageBucket: 'walltutorial-6fa05.firebasestorage.app',
  );
}
